/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DatasetRouteImport } from './routes/dataset'
import { Route as ApiDemoRouteImport } from './routes/api.demo'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiModelMetricsRouteImport } from './routes/api.model-metrics'
import { Route as ApiUploadRouteImport } from './routes/api.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetRoute = DatasetRouteImport.update({
  id: '/dataset',
  path: '/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoRoute = ApiDemoRouteImport.update({
  id: '/api/demo',
  path: '/api/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelMetricsRoute = ApiModelMetricsRouteImport.update({
  id: '/api/model-metrics',
  path: '/api/model-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dataset': typeof DatasetRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/health': typeof ApiHealthRoute
  '/api/model-metrics': typeof ApiModelMetricsRoute
  '/api/upload': typeof ApiUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dataset': typeof DatasetRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/health': typeof ApiHealthRoute
  '/api/model-metrics': typeof ApiModelMetricsRoute
  '/api/upload': typeof ApiUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dataset': typeof DatasetRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/health': typeof ApiHealthRoute
  '/api/model-metrics': typeof ApiModelMetricsRoute
  '/api/upload': typeof ApiUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dataset'
    | '/api/demo'
    | '/api/health'
    | '/api/model-metrics'
    | '/api/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dataset'
    | '/api/demo'
    | '/api/health'
    | '/api/model-metrics'
    | '/api/upload'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dataset'
    | '/api/demo'
    | '/api/health'
    | '/api/model-metrics'
    | '/api/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DatasetRoute: typeof DatasetRoute
  ApiDemoRoute: typeof ApiDemoRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiModelMetricsRoute: typeof ApiModelMetricsRoute
  ApiUploadRoute: typeof ApiUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset': {
      id: '/dataset'
      path: '/dataset'
      fullPath: '/dataset'
      preLoaderRoute: typeof DatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo': {
      id: '/api/demo'
      path: '/api/demo'
      fullPath: '/api/demo'
      preLoaderRoute: typeof ApiDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model-metrics': {
      id: '/api/model-metrics'
      path: '/api/model-metrics'
      fullPath: '/api/model-metrics'
      preLoaderRoute: typeof ApiModelMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DatasetRoute: DatasetRoute,
  ApiDemoRoute: ApiDemoRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiModelMetricsRoute: ApiModelMetricsRoute,
  ApiUploadRoute: ApiUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
