/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DatasetRouteImport } from './routes/dataset'
import { Route as ModelRouteImport } from './routes/model'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiChatStatusRouteImport } from './routes/api.chat-status'
import { Route as ApiDemoRouteImport } from './routes/api.demo'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiModelMetricsRouteImport } from './routes/api.model-metrics'
import { Route as ApiUploadRouteImport } from './routes/api.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetRoute = DatasetRouteImport.update({
  id: '/dataset',
  path: '/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStatusRoute = ApiChatStatusRouteImport.update({
  id: '/api/chat-status',
  path: '/api/chat-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoRoute = ApiDemoRouteImport.update({
  id: '/api/demo',
  path: '/api/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelMetricsRoute = ApiModelMetricsRouteImport.update({
  id: '/api/model-metrics',
  path: '/api/model-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/dataset': typeof DatasetRoute
  '/model': typeof ModelRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-status': typeof ApiChatStatusRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/health': typeof ApiHealthRoute
  '/api/model-metrics': typeof ApiModelMetricsRoute
  '/api/upload': typeof ApiUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/dataset': typeof DatasetRoute
  '/model': typeof ModelRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-status': typeof ApiChatStatusRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/health': typeof ApiHealthRoute
  '/api/model-metrics': typeof ApiModelMetricsRoute
  '/api/upload': typeof ApiUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/dataset': typeof DatasetRoute
  '/model': typeof ModelRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-status': typeof ApiChatStatusRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/health': typeof ApiHealthRoute
  '/api/model-metrics': typeof ApiModelMetricsRoute
  '/api/upload': typeof ApiUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analysis'
    | '/dashboard'
    | '/dataset'
    | '/model'
    | '/api/chat'
    | '/api/chat-status'
    | '/api/demo'
    | '/api/health'
    | '/api/model-metrics'
    | '/api/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analysis'
    | '/dashboard'
    | '/dataset'
    | '/model'
    | '/api/chat'
    | '/api/chat-status'
    | '/api/demo'
    | '/api/health'
    | '/api/model-metrics'
    | '/api/upload'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analysis'
    | '/dashboard'
    | '/dataset'
    | '/model'
    | '/api/chat'
    | '/api/chat-status'
    | '/api/demo'
    | '/api/health'
    | '/api/model-metrics'
    | '/api/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalysisRoute: typeof AnalysisRoute
  DashboardRoute: typeof DashboardRoute
  DatasetRoute: typeof DatasetRoute
  ModelRoute: typeof ModelRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatStatusRoute: typeof ApiChatStatusRoute
  ApiDemoRoute: typeof ApiDemoRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiModelMetricsRoute: typeof ApiModelMetricsRoute
  ApiUploadRoute: typeof ApiUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset': {
      id: '/dataset'
      path: '/dataset'
      fullPath: '/dataset'
      preLoaderRoute: typeof DatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-status': {
      id: '/api/chat-status'
      path: '/api/chat-status'
      fullPath: '/api/chat-status'
      preLoaderRoute: typeof ApiChatStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo': {
      id: '/api/demo'
      path: '/api/demo'
      fullPath: '/api/demo'
      preLoaderRoute: typeof ApiDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model-metrics': {
      id: '/api/model-metrics'
      path: '/api/model-metrics'
      fullPath: '/api/model-metrics'
      preLoaderRoute: typeof ApiModelMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalysisRoute: AnalysisRoute,
  DashboardRoute: DashboardRoute,
  DatasetRoute: DatasetRoute,
  ModelRoute: ModelRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatStatusRoute: ApiChatStatusRoute,
  ApiDemoRoute: ApiDemoRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiModelMetricsRoute: ApiModelMetricsRoute,
  ApiUploadRoute: ApiUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
